# Generated by Django 5.2.8 on 2026-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publisled_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
